"""Convert flat PPTX slide JSON into slide layout JSON.

Usage:
    uv run python pptx_json_to_layouts.py -i pptx.json -o assets/layouts.json
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


DEFAULT_SLIDE_SIZE = {"width": 1280.0, "height": 720.0}


def convert_pptx_json_to_layouts(pptx_json: dict[str, Any]) -> dict[str, Any]:
    """Wrap each slide's elements in one component under one layout."""

    slides = pptx_json.get("slides")
    if not isinstance(slides, list):
        raise ValueError("input JSON must contain a 'slides' array")

    slide_size = _slide_size(pptx_json.get("size"))

    return {
        "layouts": [
            _convert_slide_to_layout(
                slide=slide,
                slide_number=slide_number,
                slide_size=slide_size,
            )
            for slide_number, slide in enumerate(slides, start=1)
        ]
    }


def _convert_slide_to_layout(
    *,
    slide: Any,
    slide_number: int,
    slide_size: dict[str, float],
) -> dict[str, Any]:
    elements = _slide_elements(slide, slide_number)

    return {
        "id": f"slide_{slide_number}",
        "description": f"Full slide layout converted from PPTX slide {slide_number}.",
        "components": [
            {
                "id": "slide_content",
                "description": (
                    "Single component containing every element from "
                    f"PPTX slide {slide_number}."
                ),
                "position": {"x": 0.0, "y": 0.0},
                "size": slide_size,
                "elements": elements,
            }
        ],
    }


def _slide_elements(slide: Any, slide_number: int) -> list[Any]:
    if isinstance(slide, list):
        return slide

    if isinstance(slide, dict) and isinstance(slide.get("elements"), list):
        return slide["elements"]

    raise ValueError(
        f"slide {slide_number} must be an element array or object with an 'elements' array"
    )


def _slide_size(value: Any) -> dict[str, float]:
    if not isinstance(value, dict):
        return DEFAULT_SLIDE_SIZE.copy()

    width = _number(value.get("width"))
    height = _number(value.get("height"))
    if width is None or height is None:
        return DEFAULT_SLIDE_SIZE.copy()

    return {"width": width, "height": height}


def _number(value: Any) -> float | None:
    if isinstance(value, bool):
        return None

    if isinstance(value, (int, float)):
        return float(value)

    return None


def _read_json(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as file:
        data = json.load(file)

    if not isinstance(data, dict):
        raise ValueError("input JSON root must be an object")

    return data


def _write_json(path: Path, data: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as file:
        json.dump(data, file, indent=2)
        file.write("\n")


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(
        description="Convert PPTX JSON slides into layouts with one component per slide.",
    )
    parser.add_argument(
        "-i",
        "--input",
        required=True,
        type=Path,
        help="Path to pptx.json generated by pptx_to_json.py.",
    )
    parser.add_argument(
        "-o",
        "--output",
        required=True,
        type=Path,
        help="Path to write layouts.json.",
    )
    args = parser.parse_args(argv)

    layouts = convert_pptx_json_to_layouts(_read_json(args.input))
    _write_json(args.output, layouts)
    print(f"Saved layouts JSON to {args.output}", flush=True)


if __name__ == "__main__":
    main()
